language: java

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - master

install:
- mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- # do stuff with open Java 8
- jdk_switcher use openjdk8
- mvn clean
- mvn test