language: java

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - master

before_script:
- export DISPLAY=:99
- sh /etc/init.d/xvfb start

install:
- mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- # do stuff with open Java 8
- jdk_switcher use openjdk8
- mvn clean package jacoco:report

after_success:
- mvn coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN
- mvn sonar:sonar -Dsonar.projectKey=insukChoi_gooscodeTDD -Dsonar.organization=insukchoi-github -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN